server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.106.162.118:3306/sta_auth?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 12345679
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
logging:
  level:
    org.springframework.security: DEBUG