server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://47.106.162.118:3306/sta_project?autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&characterEncoding=utf-8
    username: root
    password: 12345679
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework.security: DEBUG